# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: CheckOut
        uses: actions/checkout@master

      # Runs a single command using the runners shell
      - name: Install Requestments
        run: pip install requests

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: python ./gfw_list.py && exit 0
      - name: Test Exit code
        run: echo "xxxx"
